#!python3
#-*- coding:utf-8 -*-#
import os

g = os.walk(".")

for path, dir_list, file_list in g:
    if path.startswith("./build/") or path.startswith("./.git") or path.startswith("./tests"):
        continue
    for file_name in file_list:
        cppfile = False 
        for ext in [".h", ".cpp", ".cc", ".c", ".hpp", ".cxx", "hxx"]:
            if file_name.endswith(ext):
                cppfile = True
                break
        if not cppfile:
           continue 
        file_path = path+"/"+file_name
        print("formatting .... " + file_path) 
        os.system("clang-format -style=file -i '%s'" % (file_path))
